language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alejogaci
  password:
    secure: gCVKdPRvwYe3hDM3nkberG9G4hRu6nbgaxtEKBaK6kivgUoeNTsxkFZz3T9FomZ8UyqPIksNaIFK/PeVVtuPCA5dxopjDumPiP7inSpRLNVyo2e6DboqlcYS8sCFSCw+HoNsxJ+fjmPv0VDU5oYrAQaFSZpZrBfqX1zOtdTsR3zLpVGU3kC4PeMlVzgoxpZDMu6DsQvrCYMqceATqu2BQusvQoxapRGCYh8NzLg7Pisple1OUDXw37uBdK4wmZuThdtlgy61M7gXhAxrIv9cq5oAn+KZwGZIh23zBbg4b8dt0tqXe7UU1RO/LJOCipBwFFB/jIT5qf0UhH/PNJFtIsS4jLQfF7kK7Rc1OWL47WJ4QPmd0LeRPe4gkAsWRrBCi1SksjN67LtxZT7qZ8kx85xAHCopC2ON0mfWNI5ylzwXqEdDdkSK/syGIaW48mBhFcyPs35ihrgjdLn6fRonDQi09bcdCPxOcJuvOdImf2iWRfjrRzvJhXfv/65z+XrnmwP2Uqb+eIqUehiYCNTPlQED0FKE/gUiShwWGMuHX80ogEsm0UdnO2iYOw28Bw1f+z2DgrRGHLv7APPaQeT8jHpbo9nXHTMfuTHaF96e3DrrT1QRbsBaNg3d5CP7gntgfJJiy5yLb1BwAImIFoHKIAZR+SLB+rBfgaIim8wLj0A=
  on:
    tags: true
    repo: alejogaci/caesar_deco
    python: 3.6
